"""Per-type recurrent decoder conditioned on target spatiotemporal coordinates.

The decoder is seeded with the (graph-fused) instance embedding and driven step by
step by an exogenous input that encodes the desired target time and location. This
matches the spec: forecasts are generated by *conditioning on the desired target
spatiotemporal coordinates*, not by feeding back previous predictions.
"""

from __future__ import annotations

import torch
from torch import nn


class PerTypeDecoder(nn.Module):
    def __init__(
        self,
        cond_dim: int,
        hidden_dim: int,
        out_dim: int,
        num_layers: int = 1,
        dropout: float = 0.0,
    ):
        super().__init__()
        self.gru = nn.GRU(
            input_size=cond_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Linear(hidden_dim, out_dim)
        self.num_layers = num_layers
        self.hidden_dim = hidden_dim

    def forward(self, h0: torch.Tensor, cond: torch.Tensor) -> torch.Tensor:
        """h0: (B*N, hidden_dim) — per-instance state from stages 1-2.
        cond: (B*N, T_f, cond_dim) — per-step exogenous conditioning.
        returns: (B*N, T_f, out_dim) normalized predictions.
        """
        h = h0.unsqueeze(0).expand(self.num_layers, -1, -1).contiguous()
        out, _ = self.gru(cond, h)
        return self.head(out)
